### ISSUE TITLE
Send updates only when attributes change

### ISSUE THREAD

**Issue by Ulydev** [OpherV/Incheon#21]
It would be a great improvement in performance and bandwidth usage if the server only sent updates of attributes that have changed, e.g. position or velocity.
Right now it's sending the whole DynamicObject even if it hasn't moved since the last update.

**Comment by namel** [comment]
As a first implementation, I'm changing the server to send updates
for objects which have changed. i.e. if at least one attribute changed, the object
will be broadcast.

This is not as optimal as suggested, but actually works better on games
which are position-sensitive.  By assuming that the entire netscheme is transmitted,
we don't need to flag which attributes are included in the event.  And the
object gets tightly packed.

The fix will also send a "complete sync" when a new player has joined.

**Comment by namel** [comment]
Fixed with commit 858fe60ebae57104143d6259b75390c44376222e
