### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Poea** [OpherV/Incheon#22]
I cant seem to build the project with web pack,it says the build parameters do not match webpacks norms.And i scoured the entire documentation,nothing states anything about what particular type of web pack to use

**Comment by namel** [comment]
Incheon doesn't build by itself (it's a library + server).  What usually happens is that you start with a game and build it.
For example, here is a game that builds with incheon, using webpack.  Does it work for you?

https://github.com/opherv/spaaace

**Comment by Poea** [comment]
I opend the issue in the wrong repo it seems,but yes that's what i talking about,It does not build for me

**Comment by OpherV** [comment]
Please open an issue on the proper repo, along with the command you're trying to run and the output you receive
