### ISSUE TITLE
In the My First Game: Pong tutorial, MyGameEngine needs to be changed to NetpongGameEngine to work

### ISSUE THREAD

**Issue by glang** [OpherV/Incheon#28]
I'm not sure why, but I needed to change "MyGameEngine" to "NetpongGameEngine" in MyGameEngine.js in order to get the game working.

**Comment by OpherV** [comment]
I just ran through the tutorial to double check - it works fine for me.
Is there a chance you mixed up the contents of the tutorial, and the contents of the [finished example](https://github.com/opherv/netpong)?

If not can you give a link to your repo and I'll have a look?

**Comment by glang** [comment]
@OpherV Ah, I must have messed up somewhere. I just redid my MyGameEngine.js again following the tutorial and it did indeed work fine. Sorry about that!
