### ISSUE TITLE
Interpolate strategy not syncing additional netScheme properties

### ISSUE THREAD

**Issue by javilumbrales** [OpherV/Incheon#39]
I noticed that when setting this strategy, any additional properties set in netScheme doesn't get synced. Digging in the code noticed that there are's a call to `syncTo` only when the object is created but further updates only update the position. Temporarily work-around extending `interpolate` method on the dynamic object as follows, ie:

    class myobject extends DynamicObject {
    interpolate(nextObj, playPercentage, worldSettings) {
       super.interpolate(nextObj, playPercentage, worldSettings);
       this.height = nextObj.height;
       this.health = nextObj.health;
       this.shield = nextObj.shield;
       this.kind = nextObj.kind;
       this.skills = nextObj.skills;
    } 
    }

**Comment by namel** [comment]
This is a critical bug.  I will create a hotfix for this.

**Comment by javilumbrales** [comment]
wow, that was super quick! Thank you very much @namel :)
