### ISSUE TITLE
babel / es5 compatability

### ISSUE THREAD

**Issue by GGAlanSmithee** [OpherV/Incheon#41]
Thanks for this inspiring project!

Currently, it seems to not be possible to use this module with babel (or in an es5 environments), since it exports es6 code (`class`es etc). There is no `engine` requirements specified in the `package.json` file, so I cannot be sure what your intentions are, but the general consensus is to transpile your code to be es5 compatable, unless othervise stated. I think there are two options to solve this:

1. Bundle and transpile your code, and export that bundle through `main` (and `module` / `jsnext:main` if you were to add es6 module exports)
2. State in your docs, and in your `package.json` `engine` section that this module is not es5 compatable

With option 2, babel users can still use your package if they transpile it (babel ignores node_modules by default), but from a user's perspective, option 1 is much more frictionless.

**Comment by namel** [comment]
Hi Alan, thanks for the issue, I'm a big fan of your work. :)

Incheon is not meant to be packaged independently.  It is a library which ultimately gets packaged into
a host game project.  There are examples for both browserify and webpack packaging.
Take a look at the boilerplate game repository: https://github.com/namel/incheongame
Or better yet, you're invited to walk through one of the tutorials in the documentation:
http://docs.incheon.gg/develop/index.html

**Comment by GGAlanSmithee** [comment]
@namel ;)

I am not so much talking about packaging as transpiling.

The problem is that using babel, it expects code to be either es5 compatable, or transpiled (which is basically the same thing). Since incheon exports es6 code (`class`), and is not transpiled by default (babel ignores node_modules) babel cannot handle when you do something like:

```
const GameEngine = require('incheon').GameEngine
class MyGameEngine extends GameEngine { }
```

I've put together a reproduction repo to better illustrate the problem: https://github.com/GGAlanSmithee/incheon-babel-test

**Comment by namel** [comment]
What about the option of configuring webpack with  `babel-loader`?  We used this to
get babel/webpack to work together, and extended the `GameEngine` class as you described above.

@OpherV got this to work by specifying the webpack `babel-loader` in `webpack.config.js`

Take a look at our spaaace demo repository, and specifically at the `webpack.config.js` file:

https://github.com/OpherV/spaaace

**Comment by GGAlanSmithee** [comment]
@namel yeah, looks like you are manually including incheon for transpilation in that project https://github.com/OpherV/spaaace/blob/master/webpack.config.js#L25

**Comment by namel** [comment]
would be great

**Comment by GGAlanSmithee** [comment]
@namel #42 (what a magic number) let me know if want anything to be changed.
